---
adjacent_list:
  0:
    - 1
  1:
    - 2
    - 3
    - 4
  2:
    - 5
  3:
    - 6
    - 7
  4:
    - 8
  5:
    - 9
  6:
    - 9
  7:
    - 9
  8:
    - 9
  9:
    - 10

miu_list:
  1: 0.250
  2: 0.25
  3: 0.01500
  4: 100
  5: 1.20
  6: 0.01000
  7: 10
  8: 0.1000
  9: 0.500

transition_proba_all:
  0:
    1: 1
  1:
    2: 0.3
    3: 0.3
    4: 0.4
  2:
    5: 1
  3:
    6: 0.5
    7: 0.5
  4:
    8: 1
  5:
    9: 1
  6:
    9: 1
  7:
    9: 1
  8:
    9: 1
  9:
    10: 1

active_cap: 5
deactive_cap: 0.12

num_queues: 5

buffer_size_for_each_queue:
  0: 5000
  1: 5000
  2: 5000
  3: 5000
  4: 5000
  5: 5000
  6: 5000
  7: 5000
  8: 5000
  9: 5000
  10: 5000
  11: 5000
  12: 5000

arrival_rate: [0.3]

max_agents: inf

sim_jobs: 100

max_arr_rate_list: [375, 375, 375]

entry_nodes: [[0,1]]